[tox]
envlist = type,py3{8,9,10,11,12,13,14}
package = editable


[testenv]
commands = pytest {posargs}
deps = -r dev-requirements.txt


[testenv:type]
deps =
	mypy
	pyright
	-r dev-requirements.txt

commands =
	mypy typelets
	pyright typelets
